import 'classes.dart';

// VETTED
final mondayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Thai BBQ chicken salad with rainbow slaw, bean sprouts, cucumber, rice noodles, red onion, fried onion, mint, lime', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads including gluten-free bread', gluten_free:true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced salami, pickles, avocado, sauerkraut, cucumber', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Chicken & leek pie', lunch: true),
  FoodItem(text: 'Mushroom & kale frittata', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, edamame, asparagus, snow pea sprouts, pumpkin seed', low_gluten: true, dairy_free: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Baked market fish with eggplant caponata & couscous', dairy_free: true, dinner: true),
  FoodItem(text: 'Fried chicken katsu with pickled ginger, kewpie mayonnaise & toasted sesame seeds', dairy_free: true, dinner: true),
  FoodItem(text: 'Ricotta & potato gnocchi with zucchini sauce, baby peas & mint', veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', gluten_free: true, veg: true, dessert: true),
];

//VETTED
final tuesdayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, roasted fresh tomatoes, baked beans & tomato spaghetti', dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, breakfast: true),
  FoodItem(text: 'Chicken noodle soup', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Spiced sweet potato salad with charred corn, pickled radish, green beans, fresh mint & ranch dressing', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced roast beef, roasted peppers, pickles, red cabbage', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Herb-crusted chicken breast schnitzel with mushy peas & brown gravy', dairy_free: true, lunch: true),
  FoodItem(text: 'Baharat-spiced tofu with falafel, zucchini hummus and quinoa', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Chicken Caesar salad with grilled chicken, beef bacon, baby cos, croutons, boiled egg, Parmesan cheese, chives', dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Beef bolognese with penne pasta, Parmesan cheese & basil', dinner: true),
  FoodItem(text: 'Thai fish curry with steamed greens, baby corn', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Indian butter squash', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Butterscotch pudding with caramel sauce', veg: true, dessert: true),
];

//VETTED
final wednesdayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Miso fish salad with soybeans, green peas & broccoli with barley, baby spinach', dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', low_gluten: true, dairy_free: true, veg: true, lunch: true),
  FoodItem(text: 'Pulled beef wrap with sriracha mayonnaise, dill cucumber, roasted red peppers, baby tatsoi', dairy_free: true, lunch: true),
  FoodItem(text: 'Mushrooms in thyme & garlic bechamel with sautéed kale, pecorino & creamy sauce', veg: true, lunch: true),
  FoodItem(text: 'Roasted free-range chicken ciabatta with garlic aioli, iceberg lettuce, pickled red cabbage, guindilla chilies', dairy_free: true, lunch: true),
  FoodItem(text: 'Sea salt crisps & sweet potato crisps', veg: true, lunch: true),
  FoodItem(text: 'Fusilli pasta salad with basil pesto, cherry tomatoes, bocconcini, radicchio, Kalamata olives, pine nuts', veg: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Carne asado of tender flank steak with pumpkin seed sauce', low_gluten: true, dinner: true),
  FoodItem(text: 'Sweet & sour chicken with pineapple, red capsicum, shallots', dairy_free: true, dinner: true),
  FoodItem(text: 'Mushroom bolognese with penne pasta & basil', veg: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Cheesecake with butter crumbs and blueberry coulis', veg: true, dessert: true),
];

// VETTED
final thursdayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, baked beans & tomato spaghetti', dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef bacon & beef sausages', dairy_free: true, breakfast: true),
  FoodItem(text: 'Roasted peaches & bocconcini salad with green beans, pomegranates basil, baby gem leaves & yogurt', veg: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', veg: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced pastrami, cucumber, avocado, spinach, tuna', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Peri peri chicken with red rice, green beans & spicy peri peri sauce', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Yellow lentil & paneer dal with rice & stir-fried bok choy', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Garden salad with poached chicken, green basil', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Moroccan lamb with golden raisins, harissa & lentil pilaf', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Khao soi chicken noodle curry with baby corn, snake beans & Thai basil', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Dry red curry of pumpkin, snake beans, lychees with pickled vegetables', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Belgian chocolate brownie', veg: true, dessert: true),
];

// VETTED
final fridayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Minestrone soup', dairy_free: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Roasted harissa chicken salad with cucumber, ginger, chili & rainbow slaw with fresh herbs', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced turkey, egg, mushroom, red cabbage, tuna', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Beef sausages with onion gravy and rosemary potatoes', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Eggplant parmigiana - baked with mozzarella cheese and tomato sugo', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Greek salad with roma tomato, Lebanese cucumber, Spanish onion, capsicum, Kalamata olives & feta', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Lamb ragu, orecchiette with Parmesan', dinner: true),
  FoodItem(text: 'Indian butter chicken with steamed jasmine rice', low_gluten: true, dinner: true),
  FoodItem(text: 'Spinach and ricotta cannelloni with tomato sugo', veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Bread and butter pudding with custard', veg: true, dessert: true),
];

// VETTED
final saturdayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, roasted mushrooms, baked beans & tomato spaghetti', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, brunch: true),
  FoodItem(text: 'Waffles with maple syrup', veg: true, brunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Heirloom tomato, cucumber & radicchio panzanella bread salad with orange, radish', dairy_free: true, lunch: true),
  FoodItem(text: 'Lasagna of layered beef mince, tomato sauce, bechamel, fresh herbs, mozzarella & parmesan', lunch: true),
  FoodItem(text: 'Vegetable gyoza, green tea noodles, shiitake, pickled ginger & soy', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Rocket with crispy beef bacon, roma tomatoes', dairy_free: true, gluten_free: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Lemon & herb chicken breast fillet with capers & dill', dairy_free: true, dinner: true),
  FoodItem(text: 'Sesame crusted market fish fillet with soba noodles, snow peas, shiitake mushrooms, ponzu', dairy_free: true, dinner: true),
  FoodItem(text: 'Broccoli & kale with black beans, spiced corn & shredded red cabbage', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Chocolate mousse with mixed berry compote', veg: true, low_gluten: true, dessert: true),
];

// VETTED
final sundayW1 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, hash browns & baked beans', veg: true, brunch: true),
  FoodItem(text: 'Beef bacon', brunch: true),
  FoodItem(text: 'Corn fritters', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Marinated beef brisket in red bean, honey & soy salad with pickled daikon, wild rice, wasabi aioli & nori, togarashi spice', dairy_free: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Spiced beef brisket with brown rice, smoky corn, black beans & pickled red cabbage', dairy_free: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Four cheese ravioli, pumpkin, sage, pine nuts, brown butter sauce', veg: true, lunch: true),
  FoodItem(text: 'Superfood salad with turmeric cauliflower, pumpkin, green beans, red quinoa, fresh mint, spinach & minted yogurt', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Spicy lamb meatballs with black mole, polenta & chimichurri', low_gluten: true, dinner: true),
  FoodItem(text: 'Yellow chicken, roasted coconut, spiced yogurt with green chili relish', low_gluten: true, dinner: true),
  FoodItem(text: 'Sweet potato & chickpea korma with coconut', veg: true, low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potatoes', veg: true, dinner: true),
  FoodItem(text: 'Eton Mess with fresh seasonal berries, meringue and chantilly cream', veg:true, low_gluten: true, dessert: true),
];

// VETTED
final mondayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, edamame, asparagus, snow pea sprouts, pumpkin seed', veg: true, dairy_free: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced salami, pickles, avocado, sauerkraut, cucumber', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Beef & mushroom pie', lunch: true),
  FoodItem(text: 'Roasted vegetable & feta frittata', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Thai BBQ chicken salad with rainbow slaw, bean sprouts, cucumber, rice noodles, red onion, fried onion, mint, lime & Nam Jim dressing', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Chicken and ricotta cannelloni baked in a rich tomato sauce', dinner: true),
  FoodItem(text: 'Malaysian satay chicken with Asian greens', low_gluten: true, dinner: true),
  FoodItem(text: 'Mushroom Bolognese with angel hair pasta', veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', veg: true, gluten_free: true, dessert: true),
];

// VETTED
final tuesdayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, potato gems, baked beans & tomato spaghetti', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, low_gluten: true, breakfast: true),
  FoodItem(text: 'Lentil soup', veg: true, dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Chicken caesar salad with grilled chicken, beef bacon, baby cos, croutons, boiled egg, parmesan cheese, chives', lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced roast beef, roasted peppers, pickles, red cabbage', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Fish burgers with sweet potato fries, baby cos lettuce & house made tartare sauce', dairy_free: true, lunch: true),
  FoodItem(text: 'Spanakopita casserole with spinach & feta cheese', veg: true, lunch: true),
  FoodItem(text: 'Spiced sweet potato salad with charred corn, pickled radish, green beans, fresh mint & ranch dressing', low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Chicken parmigiana with rich tomato sauce & grilled cheese', dinner: true),
  FoodItem(text: 'Steamed fish in ginger with a soba noodle stir fry', dairy_free: true, dinner: true),
  FoodItem(text: 'Japanese Curry with potato & carrots', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Butterscotch pudding with caramel sauce', veg: true, dessert: true),
];

// VETTED
final wednesdayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Fusilli pasta salad with basil pesto, cherry tomatoes, bocconcini, radicchio, kalamata olives, olive oil & pine nuts', veg: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Egg florentine wrap with baby spinach & parmesan cheese', veg: true, lunch: true),
  FoodItem(text: 'Shaved turkey on rye bread with cucumber, pickled red cabbage, spiced tomato kasoundi & mixed leaves', dairy_free: true, lunch: true),
  FoodItem(text: 'Chunky tuna panini with avocado, lemon, chive mayonnaise & shaved fennel', dairy_free: true, lunch: true),
  FoodItem(text: 'Sea salt crisps & sweet potato crisps', lunch: true),
  FoodItem(text: 'Miso fish salad with soy beans, green peas & broccoli with barley, baby spinach & ponzu dressing', dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Home style lamb casserole with chunks of lamb stewed to tender', low_gluten: true, dinner: true),
  FoodItem(text: 'Red curry beef with stir fry', low_gluten: true, dinner: true),
  FoodItem(text: 'Lentil and mushroom pasta in a rich tomato sauce', veg: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Cheesecake with butter crumbs and blueberry coulis', veg: true, dessert: true),
];

// VETTED
final thursdayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, roasted fresh tomatoes, baked beans & tomato spaghetti', dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef sausages', dairy_free: true, breakfast: true),
  FoodItem(text: 'Garden salad with poached chicken, green basil', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced pastrami, cucumber, avocado, spinach, tuna', dairy_free: true, lunch: true),
  FoodItem(text: 'Charred beef with rice noodles, greens & fiery sambal', low_gluten: true, lunch: true),
  FoodItem(text: 'Warm lentil and potato salad with chat potatoes, avocado & English spinach', veg: true, low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Roasted peaches & bocconcini salad with green beans, pomegranates basil, baby gem leaves & yoghurt, miso dressing', low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Basil and mustard beef with slow cooked potato', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Lamb stir fry with chilli & mint', low_gluten: true, dinner: true),
  FoodItem(text: 'Spiced braised tofu with greens & rice', veg: true, low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Belgium chocolate brownie', veg: true, dessert: true),
];

// VETTED
final fridayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'French onion soup', veg: true, lunch: true),
  FoodItem(text: 'Greek salad with roma tomato, Lebanese cucumber, Spanish onion, capsicum, Kalamata olives & feta', veg: true, gluten_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten-free bread', veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced turkey, egg, mushroom, red cabbage, tuna', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Red chicken broth with egg noodles, sliced Char Siu & Asian greens', dairy_free: true, lunch: true),
  FoodItem(text: 'Ramen noodle soup with tasty brown noodles & Asian vegetables', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Roasted harissa chicken salad with cucumber, ginger, chili & rainbow slaw with fresh herbs & garlic toum dressing', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Jacket potato topped with Mexican ground beef, sour cream & guacamole', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Chicken Pad Siu with stir fry flat noodles & crushed nuts', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Tofu Pad Siu with stir fry flat noodles & crushed nuts', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Bread & butter pudding with custard', veg: true, dessert: true),
];

// VETTED
final saturdayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, roasted mushrooms, baked beans & tomato spaghetti', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, brunch: true),
  FoodItem(text: 'Waffles with maple syrup', veg: true, brunch: true),
  FoodItem(text: 'Rocket with crispy beef bacon, roma tomatoes', dairy_free: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Greek chicken gyros with tzatziki & wild rice', lunch: true),
  FoodItem(text: 'Smoked tofu and hummus with tofu, pilaf rice & pickled vegetables', veg: true, low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Heirloom tomato, cucumber & radicchio panzanella bread salad with orange, radish & sherry dressing', veg: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Pulled beef nachos topped with salsa, sour cream & guacamole', dinner: true),
  FoodItem(text: 'Soy and orange chicken stir fry with egg noodles', dairy_free: true, dinner: true),
  FoodItem(text: 'Adobo mushroom tacos filled with onion, garlic & herbs', veg: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Chocolate mousse with mixed berry compote', veg: true, low_gluten: true, dessert: true),
];

// VETTED
final sundayW2 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, hash browns & baked beans', veg: true, brunch: true),
  FoodItem(text: 'Beef bacon', brunch: true),
  FoodItem(text: 'Corn fritters', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Superfood salad with turmeric cauliflower, pumpkin, green bean, red quinoa, fresh mint, spinach & minted yoghurt', veg: true, low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits & fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Chicken paella with veggies & rice cooked in a saffron broth', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Mexican stuffed peppers with tortilla chips, sour cream & salsa', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Marinated beef brisket in red bean, honey & soy salad with pickled daikon, wild rice, wasabi aioli & nori, togarashi spice', dairy_free: true, gluten_free: true, dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Asparagus and chicken quiche with seasonal vegetables', dinner: true),
  FoodItem(text: 'Hainanese chicken served with fresh herbs & Asian greens', dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Mushroom and cashew cream pasta', veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Eton Mess with fresh seasonal berries, meringue and chantilly cream', veg: true, low_gluten: true, dessert: true),
];

final mondayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Thai BBQ chicken salad with rainbow slaw, bean sprouts, cucumber, rice noodles, red onion, edamame, lime', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten free bread', veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced pickles, avocado, sauerkraut, cucumber', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Shepherd’s pie', lunch: true),
  FoodItem(text: 'Miso mushroom and leek quiche', veg: true, lunch: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, edamame, asparagus, snow pea sprouts, pumpkin seed', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Selection of rice and garden components', veg: true, dinner: true),
  FoodItem(text: 'Swedish meatballs with slow cooked potatoes in a rich red sauce', low_gluten: true, dinner: true),
  FoodItem(text: 'Coconut and beef stir fry', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Eggplant parmigiana topped with salsa and melted cheese', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', veg: true, gluten_free: true, dessert: true),
];

final tuesdayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, hash browns, baked beans & tomato spaghetti', dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, breakfast: true),
  FoodItem(text: 'Butternut squash soup', veg: true, lunch: true),
  FoodItem(text: 'Spiced sweet potato salad with charred corn, pickled radish, green beans, fresh mint and ranch dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components & breads, including gluten free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced roast beef, roasted peppers, pickles, red cabbage', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Tandoori chicken, steamed rice and mint yoghurt', low_gluten: true, lunch: true),
  FoodItem(text: 'Aloo Gobi with potatoes, cauliflower and rice', veg: true, low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Chicken Caesar salad with grilled chicken, beef bacon, baby cos, croutons, boiled egg, parmesan cheese and Caesar dressing', dinner: true),
  FoodItem(text: 'Selection of fruits & garden components', veg: true, dinner: true),
  FoodItem(text: 'Beef osso buco slow cooked in a rich sauce', dinner: true),
  FoodItem(text: 'Crispy chicken stir fry with chilli and basil', dairy_free: true, dinner: true),
  FoodItem(text: 'Omelette with stir fried mushroom and rice', veg: true, gluten_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Butterscotch pudding with caramel sauce', veg: true, dessert: true),
];

final wednesdayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Miso fish salad with soybeans, green peas, broccoli, barley and baby spinach', lunch: true),
  FoodItem(text: 'Selection of seasonal fruits and fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Eggplant chips wrap with miso hummus, alfalfa, slaw and spiced yogurt', veg: true, lunch: true),
  FoodItem(text: 'Portuguese roast chicken baguette with avocado, pepper, mayonnaise, tomato and baby spinach', lunch: true),
  FoodItem(text: 'Pastrami focaccia with gruyere cheese, slaw, pickles, spicy aioli and sea salt crisps', lunch: true),
  FoodItem(text: 'Sea salt crisps and sweet potato crisps', veg: true, lunch: true),
  FoodItem(text: 'Fusilli pasta salad with basil pesto, cherry tomatoes, bocconcini, radicchio, kale and pine nuts', veg: true, dinner: true),
  FoodItem(text: 'Selection of fruits and garden components', veg: true, dinner: true),
  FoodItem(text: 'Lamb stew with carrots and potatoes in a hearty broth', low_gluten: true, dinner: true),
  FoodItem(text: 'Korean fish stir fry with pickles and seasonal vegetables', dairy_free: true, dinner: true),
  FoodItem(text: 'Enchiladas with charred tomatillo salsa and creamy pinto beans', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables and potato', veg: true, dinner: true),
  FoodItem(text: 'Cheesecake with butter crumbs and blueberry coulis', veg: true, dessert: true),
];

final thursdayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, potato gems, baked beans & tomato spaghetti', dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, breakfast: true),
  FoodItem(text: 'Roasted peaches and bocconcini salad with green beans, pomegranates, basil, baby gem leaves and yogurt', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components and breads, including gluten-free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced pastrami, cucumber, avocado, spinach and tuna', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Creamy pesto chicken pasta with penne pasta, capsicum and green beans', lunch: true),
  FoodItem(text: 'Cauliflower cheese pasta bake with fresh herbs and parmesancanai & stir fried bok choy', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Garden salad with poached chicken and green beans', lunch: true),
  FoodItem(text: 'Selection of fruits and garden components', veg: true, dinner: true),
  FoodItem(text: 'Bolognese lasagna with a creamy sauce and grilled cheese', dinner: true),
  FoodItem(text: 'Stir fried chicken with asparagus and oyster sauce', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Turmeric and coconut braised cabbage with chickpeas', veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables and potato', veg: true, dinner: true),
  FoodItem(text: 'Belgian chocolate brownie', veg: true, dessert: true),
];

final fridayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Split pea and chicken soup', lunch: true),
  FoodItem(text: 'Roasted harissa chicken salad with cucumber, ginger, chili and rainbow slaw with fresh herbs', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits, fresh garden components and breads, including gluten-free bread', gluten_free: true, veg: true, lunch: true),
  FoodItem(text: 'Beef pastrami, sliced cheese, sliced tomato, sliced turkey, egg, mushroom, red cabbage, tuna', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Korean fried chicken with roasted vegetables and fried rice', dairy_free: true, lunch: true),
  FoodItem(text: 'Ricotta and mint fritters with a warm potato and baby pea salad', veg: true, lunch: true),
  FoodItem(text: 'Greek salad with tomato, Lebanese cucumber, Spanish onion, capsicum, olives and feta', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits and garden components', veg: true, dinner: true),
  FoodItem(text: "Shepherd's pie packed full of meat, seasoned vegetables and creamy mashed potato", dinner: true),
  FoodItem(text: 'Spicy stir-fried squid with snake beans and baby corn', dairy_free: true, dinner: true),
  FoodItem(text: 'Butternut squash and green bean stew', veg: true, dairy_free: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables and potato', veg: true, dinner: true),
  FoodItem(text: 'Bread and butter pudding with custard', veg: true, dessert: true),
];

final saturdayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Scrambled eggs, roasted mushrooms, baked beans & tomato spaghetti', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Beef bacon', dairy_free: true, brunch: true),
  FoodItem(text: 'Waffles with maple syrup', veg: true, brunch: true),
  FoodItem(text: 'Heirloom tomato, cucumber and radicchio panzanella bread salad with orange and radish', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits and fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Beef farfalle Pasta with mushroom and rose sauce', lunch: true),
  FoodItem(text: 'Gluten-free eggplant parmigiana lasagna with roasted tomato and fennel chips', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Rocket with crispy beef bacon and Roma tomatoes', low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits and garden components', veg: true, dinner: true),
  FoodItem(text: 'Roast lamb with bubble and squeak and steamed seasonal vegetables', low_gluten: true, dinner: true),
  FoodItem(text: 'Tofu stir-fry with cucumber and ginger salad', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Creamy spinach and chickpeas with pickled cherry peppers', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables and potato', veg: true, dinner: true),
  FoodItem(text: 'Chocolate mousse with mixed berry compote', veg: true, low_gluten: true, dessert: true),
];

final sundayW3 = [
  FoodItem(text: 'Fresh juices, selection of milks, espresso coffee & selection of teas', veg: true, breakfast: true),
  FoodItem(text: 'Selection of cereals including gluten-free cereal', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee, pickles, dried shallots and vinegar', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh fruit salad of seasonal fruits, whole seasonal fruits and selection of canned fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural yogurt & flavored yogurt with plums or cocoa nibs', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads including gluten-free bread', gluten_free:true, veg: true, breakfast: true),
  FoodItem(text: 'Selection of condiments and sauces', veg: true, breakfast: true),
  FoodItem(text: 'Poached eggs, hash browns & baked beans', veg: true, brunch: true),
  FoodItem(text: 'Beef bacon', brunch: true),
  FoodItem(text: 'Corn fritters', veg: true, dairy_free: true, brunch: true),
  FoodItem(text: 'Marinated beef brisket in red bean, honey and soy salad with pickled daikon, wild rice, wasabi aioli and nori, togarashi spice', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Selection of seasonal fruits and fresh garden components', veg: true, lunch: true),
  FoodItem(text: 'Barbecued chicken pizza on fresh Afghan bread', lunch: true),
  FoodItem(text: 'Spiced tomato Afghan pizza with feta, tomato slices, potato and fresh lemon', veg: true, lunch: true),
  FoodItem(text: 'Superfood salad with turmeric cauliflower, pumpkin, green beans, red quinoa, fresh mint, spinach and minted yoghurt', low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of fruits and garden components', veg: true, dinner: true),
  FoodItem(text: 'House battered fish and chips with sweet potato fries', dairy_free: true, dinner: true),
  FoodItem(text: 'Thai style chicken with Hokkien noodles', dairy_free: true, dinner: true),
  FoodItem(text: 'Spaghetti squash bake with seasonal veg and a rich creamy sauce', dinner: true),
  FoodItem(text: 'Selection of rice, vegetables and potato', veg: true, dinner: true),
  FoodItem(text: 'Eton Mess with fresh seasonal berries, meringue and chantilly cream', veg: true, low_gluten: true, dessert: true),
];

Week week_1_2023T1 = Week(mondayW1, tuesdayW1, wednesdayW1, thursdayW1, fridayW1, saturdayW1, sundayW1);
Week week_2_2023T1 = Week(mondayW2, tuesdayW2, wednesdayW2, thursdayW2, fridayW2, saturdayW2, sundayW2);
Week week_3_2023T1= Week(mondayW3, tuesdayW3, wednesdayW3, thursdayW3, fridayW3, saturdayW3, sundayW3);

final Term term_1_2023 = Term(week_1_2023T1, week_2_2023T1, week_3_2023T1);