import '../classes.dart';

final mondayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'Chicken & leek pie with puff pastry', lunch: true),
  FoodItem(text: 'Mediterranean casserole with green peas, eggplant, celery', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Mashed potato with peas & gravy', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Tuscan tomato & capsicum soup', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Chickpea and quinoa tabouleh with lemon, tomato & parsley salad', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Baked market fish in lemongrass, coconut, ginger', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Fried chicken bites with eggplant caponata', dairy_free: true, dinner: true),
  FoodItem(text: 'Potato gnocchi with eggplant caponata', veg: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & polenta', veg: true, dinner: true),
  FoodItem(text: 'Spinach and pear salad, with onion, rocket, watermelon, broccoli & sultana', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', gluten_free: true, veg: true, dessert: true),
];


final tuesdayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, spaghetti, hash browns', veg: true, breakfast: true),
  FoodItem(text: 'Pork bacon', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'Chicken schnitzel with peas, chat potato & rich tomato sauce', lunch: true),
  FoodItem(text: 'Grilled tofu tagine with mint couscous', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Potato and seeded mustard salad with sweet potato, roasted carrots & dill', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Moroccan lamb with sultanas', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Thai green chicken curry with bamboo shoots, coriander & coconut milk', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Thai stir-fry with cauliflower, sweet potato, carrot, eggplant, chilli & coriander', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & couscous', veg: true, dinner: true),
  FoodItem(text: 'Heirloom tomato, cucumber & radicchio panzanella bread salad & orange, radish', veg: true, dinner: true),
  FoodItem(text: 'Vanilla Brulee', low_gluten: true, dessert: true, veg:true),
];


final wednesdayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'SANDWICH DAY:', title: true, lunch: true),
  FoodItem(text: '1. Choose your bread', lunch: true, override: true),
  FoodItem(text: '2. Pick your protein', lunch: true, override: true),
  FoodItem(text: '3. Add your salad', lunch: true, override: true),
  FoodItem(text: '4. Finish with your sauce', lunch: true, override: true),
  FoodItem(text: '5. Wrap or Fold', lunch: true, override: true),
  FoodItem(text: 'Butternut pumpkin & coconut soup', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Pasta salad with cherry tomatoes, bocconcini, radicchio, kalamata olives and pesto dressing', veg: true, lunch: true),
  FoodItem(text: 'Sweet & sour chicken with pineapple, red capsicum & shallots', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Baked Fish Tandoori', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Tandoori Gobi with tofu & cauliflower', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Minted tofu larb salad with toasted rice, cucumber, tomato, onion, shallot, green kale, coriander, naam jim dressing', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Tiramisu with coffee jelly', dessert: true, veg: true),
];


final thursdayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, hash browns & English muffin', veg: true, breakfast: true),
  FoodItem(text: 'Sausage patty', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'Lasagna of layered beef mince sauce, béchamel, fresh herbs, mozzarella & parmesan', lunch: true),
  FoodItem(text: 'Baked zucchini with mozzarella cheese & tomato sugo', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Roasted peaches & bocconcini salad with green beans, basil, baby gem leaves & pomegranates dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'CURRY NIGHT:', title: true, dinner: true),
  FoodItem(text: 'Chicken Masala', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Thai lamb', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Chickpea and Cabbage', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Naan bread, basmati rice & assorted vegetables', veg: true, dinner: true),
  FoodItem(text: 'Garden salad with tomato, green lettuce, Spanish onion, baby spinach, shredded carrot & cabbage', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Apple and Cinnamon Crumble', dessert: true, veg: true),
];


final fridayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'Spicy chicken Pad Thai', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Puffed tofu Pad Thai', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'On the side: chilli oil, fried shallot, pickled chilli, bean sprouts', veg: true, lunch: true),
  FoodItem(text: 'Cream of cauliflower soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Greek salad with Roma tomato, Lebanese cucumber, Spanish onion, capsicum, kalamata olives & feta', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'PIZZA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true),
  FoodItem(text: 'Chefs Pizza of the Week', dinner: true),
  FoodItem(text: 'BBQ Chicken', dinner: true),
  FoodItem(text: 'Roast capsicum, pumpkin harissa sauce, pepitas and fetta cheese', veg: true, dinner: true),
  FoodItem(text: 'Caesar salad with baby cos, boiled egg, cherry tomato and parmesan cheese', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Matcha Bread Pudding', dessert: true, veg: true),
];


final saturdayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, roasted tomato, baked beans, spaghetti', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Waffles with maple syrup', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'Beef sausages with a rich napolitana sauce & creamy mash potato', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Nachos with spiced mushroom and tomato salsa with Mexican cheese', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Waldorf salad: Iceberg, grape, celery, apple, onion, rocket & creamy French dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'PASTA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true),
  FoodItem(text: '1. Choose your pasta', dinner: true, override: true),
  FoodItem(text: '2. Pick your sauce', dinner: true, override: true),
  FoodItem(text: '3. Grab some garlic bread', dinner: true, override: true),
  FoodItem(text: '4. Sprinkle cheese', dinner: true, override: true),
  FoodItem(text: '5. Add some veggies', dinner: true, override: true),
  FoodItem(text: 'Nicoise salad: Potato, green beans, capers, onion, black olives, green lettuce green pea & capsicum', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Lemon Meringue Tart', dessert: true, veg: true),
];


final sundayW1 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, spaghetti, hash browns', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Buttermilk Pancakes', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad ingredients & condiments', lunch: true, override: true),
  FoodItem(text: 'BURGER DAY:', title: true),
  FoodItem(text: '(LG, DF, VG OPTIONS AVAILABLE)', subtitle: true),
  FoodItem(text: 'Beef Burger with shoestring fries, selection of sliced cheese, tomato, lettuce & burger sauce', low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Tofu / Veggie Burger with shoestring fries, selection of sliced cheese, tomato, lettuce & burger sauce', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Chilli bean salad with chickpea, capsicum, cucumber, lime, coriander & corn', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'CHEFS ROAST:', title: true, dinner: true),
  FoodItem(text: 'Chefs selection of roast served with seasonal vegetables, polenta & gravy', dinner: true, veg: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, snow pea sprouts, pumpkin seed', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Chocolate brownie', low_gluten: true, dessert: true, veg: true),
];


final mondayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Beef & mushroom pie with puff pastry', lunch: true),
  FoodItem(text: 'Capsicum, zucchini & tomato casserole', veg: true, lunch: true),
  FoodItem(text: 'Mashed potato with peas & gravy', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Tuscan tomato & capsicum soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Nicoise salad: Potato, green beans, capers, onion, black olives, green lettuce green pea, capsicum', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Beef stew slow cooked in a rich sauce', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Crispy chicken stir fry with chilli & basil', dairy_free: true, dinner: true),
  FoodItem(text: 'Mushroom, tofu, cabbage & pea fried rice', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Garden salad with tomato, green lettuce, Spanish onion, baby spinach, shredded carrot & cabbage', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Mango and Coconut Sago', veg: true, low_gluten: true, dessert: true),
];


final tuesdayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, spaghetti, hash browns', veg: true, breakfast: true),
  FoodItem(text: 'Pork bacon', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Beef meatballs with creamy black pepper and onion sauce & mashed potato', lunch: true),
  FoodItem(text: 'Eggs, tofu, kimchi, vegetables & brown fried rice', veg: true, low_gluten: true, dairy_free: true, lunch: true),
  FoodItem(text: 'Chickpea and quinoa tabouleh with lemon, tomato & parsley salad', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Khao soi chicken with egg noodle', dairy_free: true, dinner: true),
  FoodItem(text: 'Fishermen pie with peas and corn', dinner: true),
  FoodItem(text: 'Deep fry tofu with baby corn, green beans & thai basil', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Potato and seeded mustard salad with sweet potato, roasted carrots & dill', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Cheesecake with butter crumbs and passionfruit jelly', dessert: true, veg: true),
];


final wednesdayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'SANDWICH DAY:', title: true, lunch: true),
  FoodItem(text: '1. Choose your bread', lunch: true, override: true),
  FoodItem(text: '2. Pick your protein', lunch: true, override: true),
  FoodItem(text: '3. Add your salad', lunch: true, override: true),
  FoodItem(text: '4. Finish with your sauce', lunch: true, override: true),
  FoodItem(text: '5. Wrap or Fold', lunch: true, override: true),
  FoodItem(text: 'Butternut pumpkin & coconut soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Minted tofu larb salad, toasted rice, cucumber, tomato, onion, shallot, green kale, coriander, naam jim dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Lamb and chickpea Tagine', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Korean glazed chicken with cabbage & capsicum', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Moroccan spiced cauliflower with chickpea, apricot & zucchini', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & polenta', veg: true, dinner: true),
  FoodItem(text: 'Pasta salad with cherry tomatoes, bocconcini, radicchio, kalamata olives & pesto dressing', veg: true, dinner: true),
  FoodItem(text: 'Chai Tea Bread Pudding', dessert: true, veg: true),
];


final thursdayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, hash browns & English muffin', veg: true, breakfast: true),
  FoodItem(text: 'Sausage patty', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Mongolian beef and Singaporean noodles stir fry', dairy_free: true, lunch: true),
  FoodItem(text: 'Chinese wombok and bok choy with Singaporean noodles stir fry', veg: true, dairy_free: true, lunch: true),
  FoodItem(text: 'On the side: chilli oil, fried shallot, soy sauce', lunch: true, veg: true),
  FoodItem(text: 'Heirloom tomato, cucumber & radicchio panzanella bread salad & orange, radish', veg: true, lunch: true),
  FoodItem(text: 'CURRY NIGHT:', title: true, dinner: true),
  FoodItem(text: 'Tandoori Chicken', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Slow cook Malaysian beef massaman', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Paneer in lentil dahl', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Naan bread, basmati rice and assorted vegetables', veg: true, dinner: true),
  FoodItem(text: 'Chilli bean salad with chickpea, capsicum, cucumber, lime, coriander & corn', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Vanilla Brulee', low_gluten: true, dessert: true, veg: true),
];


final fridayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Panko crumbed chicken with Japanese curry sauce', dairy_free: true, lunch: true),
  FoodItem(text: 'Corn fritters with potato and apple curry sauce', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Cream of cauliflower soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Roasted peaches & bocconcini salad with green beans, basil, baby gem leaves & pomegranate dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'PIZZA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true),
  FoodItem(text: 'Chefs Pizza of the Week', dinner: true),
  FoodItem(text: 'Meat Lover: turkey bacon, beef salami, beef sausage, mozzarella & tomato', dinner: true),
  FoodItem(text: 'Basil, spinach, zucchini & ricotta', veg: true, dinner: true),
  FoodItem(text: 'Caesar salad with baby cos, boiled egg, cherry tomato and parmesan cheese', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', gluten_free: true, veg: true, dessert: true),
];


final saturdayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, roasted tomato, baked beans, tomato spaghetti', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Waffles with maple syrup', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Fish and Chips with tartare sauce', dairy_free: true, lunch: true),
  FoodItem(text: 'Roast vegetable lasagne', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, edamame, asparagus, snow pea sprouts & pumpkin seed', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'PASTA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true, low_gluten: true, veg: true),
  FoodItem(text: '1. Choose your pasta', dinner: true, override: true),
  FoodItem(text: '2. Pick your sauce', dinner: true, override: true),
  FoodItem(text: '3. Grab some garlic bread', dinner: true, override: true),
  FoodItem(text: '4. Sprinkle cheese', dinner: true, override: true),
  FoodItem(text: '5. Add some veggies', dinner: true, override: true),
  FoodItem(text: 'Greek salad with Roma tomato, Lebanese cucumber, Spanish onion, capsicum, kalamata olives & feta', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Chocolate brownie', low_gluten: true, dessert: true),
];


final sundayW2 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, hash browns, baked beans, spaghetti', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Buttermilk Pancakes', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Lasagna of layered beef mince sauce, béchamel, fresh herbs, mozzarella & parmesan', lunch: true),
  FoodItem(text: 'Pastizi filled with spinach and ricotta', veg: true, lunch: true),
  FoodItem(text: 'Garden salad with tomato, green lettuce, Spanish onion, baby spinach, shredded carrot & cabbage', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'CHEFS ROAST:', title: true, dinner: true),
  FoodItem(text: 'Chefs selection of roast served with seasonal vegetables, polenta & gravy', dinner: true, veg: true),
  FoodItem(text: 'Waldorf salad: Iceberg, grape, celery, apple, onion, rocket and creamy French dressing', veg: true, dinner: true),
  FoodItem(text: 'Apple and Cinnamon Crumble', dessert: true, veg: true),
];



final mondayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Beef sausage roll', lunch: true),
  FoodItem(text: 'Vegetarian sausage roll', veg: true, lunch: true),
  FoodItem(text: 'Mashed potato with peas & gravy', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Tuscan tomato & capsicum soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Thai rainbow slaw, bean sprouts, cucumber, rice noodles, red onion, fried onion, mint, lime', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Beef ravioli with tomato, green bean & broccoli', dairy_free: true, dinner: true),
  FoodItem(text: 'Stir fried chicken with asparagus & oyster sauce', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Chinese broccoli and green bean stir fried rice', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Green power salad with avocado, spinach, green beans, celery, kale, broccoli, snow pea sprouts, pumpkin seed', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Tiramisu with coffee jelly', dessert: true, veg: true),
];


final tuesdayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, spaghetti, hash browns', veg: true, breakfast: true),
  FoodItem(text: 'Pork bacon', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Chicken schnitzel parmigiana', lunch: true),
  FoodItem(text: 'Roasted eggplant topped with tomato & melted cheese', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Beetroot, green beans, radicchio, kale salad with balsamic vinegar & fetta cheese', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Basil and mustard beef with slow cooked potato', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Yellow chicken in coconut sauce with cauliflower, cabbage & chickpea', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Sweet potato frittata', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & potato', veg: true, dinner: true),
  FoodItem(text: 'Greek salad with Roma tomato, Lebanese cucumber, Spanish onion, capsicum, kalamata olives & feta', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Matcha Bread Pudding', dessert: true, veg: true),
];



final wednesdayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'SANDWICH DAY:', title: true, lunch: true),
  FoodItem(text: '1. Choose your bread', lunch: true, override: true),
  FoodItem(text: '2. Pick your protein', lunch: true, override: true),
  FoodItem(text: '3. Add your salad', lunch: true, override: true),
  FoodItem(text: '4. Finish with your sauce', lunch: true, override: true),
  FoodItem(text: '5. Wrap or Fold', lunch: true, override: true),
  FoodItem(text: 'Butternut pumpkin & coconut soup', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'Chilli bean salad with chickpea, capsicum, cucumber, lime, coriander & corn', veg: true, lunch: true),
  FoodItem(text: 'Fish Laksa with rice noodle, shredded carrots & cabbage', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Lasagna of layered beef mince sauce, béchamel, fresh herbs, mozzarella & parmesan', dinner: true),
  FoodItem(text: 'Aloo Gobi', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of rice, vegetables & polenta', veg: true, dinner: true),
  FoodItem(text: 'Potato and seeded mustard salad with sweet potato, roasted carrots and dill', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', gluten_free: true, dessert: true, veg: true),
];

final thursdayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, hash browns & English muffin', veg: true, breakfast: true),
  FoodItem(text: 'Sausage patty', breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Quiche "Lorraine" with turkey bacon', lunch: true),
  FoodItem(text: 'Vegetable quiche with leek, onion & Swiss cheese', veg: true, lunch: true),
  FoodItem(text: 'Minted tofu larb, toasted rice, cucumber, tomato,  onion, shallot, green kale, coriander & naam jim dressing', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'CURRY NIGHT:', title: true, dinner: true),
  FoodItem(text: 'Thai green chicken', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Beef Rogan Josh', low_gluten: true, dairy_free: true, dinner: true),
  FoodItem(text: 'Vegetable Korma', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Naan bread, jasmin rice and assorted vegetables', veg: true, dinner: true),
  FoodItem(text: 'Pasta salad with cherry tomatoes, bocconcini, radicchio, kalamata olives and a pesto dressing', veg: true, dinner: true),
  FoodItem(text: 'Chocolate brownie', low_gluten: true, dessert: true, veg: true),
];


final fridayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Beef meatballs with potato & salsa verde', dairy_free: true, lunch: true),
  FoodItem(text: 'Roasted vegetable frittata', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Cream of cauliflower soup', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'Chickpea and quinoa tabouleh with lemon, tomato, parsley salad', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'PIZZA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true, low_gluten: true, veg: true),
  FoodItem(text: 'Chefs Pizza of the Week', dinner: true),
  FoodItem(text: 'Hawaiian: turkey bacon, pineapple & tomato', dinner: true),
  FoodItem(text: 'Pesto, mushroom & broccoli', veg: true, dinner: true),
  FoodItem(text: 'Superfood salad with turmeric cauliflower, pumpkin, green bean, red quinoa, fresh mint, spinach', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Lemon Meringue Tart', dessert: true, veg: true),
];


final saturdayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, roasted tomato baked beans, spaghetti', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Waffles with maple syrup', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'Indonesian "Mie Goreng" fried noodle with chicken, chilli, sliced cucumber', dairy_free: true, lunch: true),
  FoodItem(text: 'Fried soybean tempeh', low_gluten: true, veg: true, lunch: true),
  FoodItem(text: 'On the side: Chilli sambal oelek, fried shallot & prawn cracker', lunch: true),
  FoodItem(text: 'Heirloom tomato, cucumber & radicchio panzanella bread salad & orange, radish', veg: true, lunch: true),
  FoodItem(text: 'PASTA NIGHT:', title: true, dinner: true),
  FoodItem(text: '(LG, VG OPTIONS AVAILABLE)', subtitle: true, dinner: true, low_gluten: true, veg: true),
  FoodItem(text: '1. Choose your pasta', dinner: true, override: true),
  FoodItem(text: '2. Pick your sauce', dinner: true, override: true),
  FoodItem(text: '3. Grab some garlic bread', dinner: true, override: true),
  FoodItem(text: '4. Sprinkle cheese', dinner: true, override: true),
  FoodItem(text: '5. Add some veggies', dinner: true, override: true),
  FoodItem(text: 'Spinach and pear salad, with onion, rocket, watermelon, broccoli & sultana', low_gluten: true, veg: true, dinner: true),
  FoodItem(text: 'Selection of ice-cream cups', gluten_free: true, dessert: true, veg: true),
];

final sundayW3 = [
  FoodItem(text: 'Selection of cereals & gluten free cereal', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Porridge with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Congee with accompaniments', gluten_free: true, dairy_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Fresh seasonal fruit salad & whole fruits', low_gluten: true, veg: true, breakfast: true),
  FoodItem(text: 'Natural & flavoured yoghurt with accompaniments', veg: true, breakfast: true),
  FoodItem(text: 'Selection of breads & gluten free bread with spreads', gluten_free: true, veg: true, breakfast: true),
  FoodItem(text: 'Eggs, baked beans, spaghetti, hash browns', brunch: true, veg: true),
  FoodItem(text: 'Turkey bacon', brunch: true),
  FoodItem(text: 'Buttermilk Pancakes', brunch: true, veg: true),
  FoodItem(text: 'Sandwich Bar: roast chicken, roast beef, turkey, sliced cheese, assorted salad fillings and condiments', lunch: true, override: true),
  FoodItem(text: 'BURGER DAY:', title: true, lunch: true),
  FoodItem(text: '(LG, DF, VG OPTIONS AVAILABLE)', subtitle: true, lunch: true, low_gluten: true, dairy_free: true, veg: true),
  FoodItem(text: 'Chicken Burger with coleslaw, sweet potato chips, selection of sliced cheese, tomato, burger sauce', lunch: true),
  FoodItem(text: 'Tofu / Veggie Burger with coleslaw sweet potato chips, selection of sliced cheese, tomato and burger sauce', veg: true, lunch: true),
  FoodItem(text: 'Waldorf salad: Iceberg, grape, celery, apple, onion, rocket & creamy French dressing', veg: true, low_gluten: true, lunch: true),
  FoodItem(text: 'CHEFS ROAST:', title: true, dinner: true),
  FoodItem(text: 'Chefs selection of roast served with seasonal vegetables, polenta & gravy', dinner: true, veg: true),
  FoodItem(text: 'Caesar salad with baby cos, boiled egg, cherry tomato and parmesan cheese', veg: true, low_gluten: true, dinner: true),
  FoodItem(text: 'Mango and Coconut Sago', low_gluten: true, veg: true, dessert: true),
];


final Week week_1_2023T2 = Week(mondayW1, tuesdayW1, wednesdayW1, thursdayW1, fridayW1, saturdayW1, sundayW1);
final Week week_2_2023T2 = Week(mondayW2, tuesdayW2, wednesdayW2, thursdayW2, fridayW2, saturdayW2, sundayW2);
final Week week_3_2023T2 = Week(mondayW3, tuesdayW3, wednesdayW3, thursdayW3, fridayW3, saturdayW3, sundayW3);

final Term term_2_2023 = Term(week_1_2023T2, week_2_2023T2, week_3_2023T2);